//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ATM.rc
//
#define IDD_ATM_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_LOGIIN               130
#define IDD_DIALOG_GETMONEY             131
#define IDD_DIALOG_MODPWD               132
#define IDD_DIALOG_PRINTINFO            133
#define IDD_DIALOG_TRANSMONEY           136
#define IDD_DIALOG_QUERY                137
#define IDD_DIALOG_MAINMENU             138
#define IDD_DIALOG_SERVE                143
#define IDD_DIALOG_WARNING              144
#define IDD_DIALOG_Mod                  155
#define IDR_WAVE_ERROR                  157
#define IDR_WAVE_WAIT                   158
#define IDR_WAVE_TAKECARD               160
#define IDR_WAVE_GETMONEY               161
#define IDR_WAVE_INPUTERROR             162
#define IDR_WAVE_CONTINUE               165
#define IDR_WAVE_INSERTCARD             166
#define IDR_WAVE_INPUT                  167
#define IDR_WAVE_INPUTPWD               168
#define IDR_WAVE_TYPE                   169
#define IDR_WAVE_WELCOM                 170
#define IDR_WAVE_MSG                    171
#define IDB_BITMAP1                     208
#define IDB_BITMAP2                     209
#define IDB_BITMAP3                     210
#define IDB_BITMAP4                     211
#define IDB_BITMAP5                     212
#define IDB_BITMAP6                     213
#define IDB_BITMAP7                     214
#define IDB_BITMAP8                     215
#define IDB_BITMAP9                     216
#define IDB_BITMAP10                    217
#define IDB_BITMAP11                    218
#define IDB_BITMAP12                    219
#define IDB_BITMAP13                    220
#define IDB_BITMAP14                    221
#define IDB_BITMAP15                    222
#define IDB_BITMAP16                    223
#define IDB_BITMAP17                    224
#define IDB_BITMAP18                    225
#define IDD_DIALOG_REGISTER             226
#define IDD_DIALOG_DEPOSIT              228
#define IDD_DIALOG_RECORD               229
#define IDC_BTN_LOGIN                   1004
#define IDC_BTN_CANCLE                  1006
#define IDC_BTN_OK                      1007
#define IDC_EDIT_GETMONEY               1010
#define IDC_STATIC_100                  1013
#define IDC_STATIC_300                  1014
#define IDC_STATIC_500                  1015
#define IDC_STATIC_800                  1016
#define IDC_STATIC_1000                 1017
#define IDC_STATIC_TIP                  1019
#define IDC_BYN_CANCLE                  1021
#define IDC_STATIC_INFO                 1021
#define IDC_BTN_BACK                    1022
#define IDC_EDIT_TRANINFO               1023
#define IDC_EDIT_TRANSINFO              1023
#define IDC_BTN_QUERY                   1026
#define IDC_BTN_GETMONEY                1027
#define IDC_BTN_MODPWD                  1028
#define IDC_BTN_CANCEL                  1028
#define IDC_BTN_DEPOSIT                 1029
#define IDC_BTN_TRANSMONEY              1030
#define IDC_BTN_EXIT                    1031
#define IDC_BTN_SERVE                   1032
#define IDC_BTN_MAINMENU                1032
#define IDC_BTN_REMAINMONEY             1033
#define IDC_BTN_HISTORY                 1034
#define IDC_BTN_PRINTINFO               1035
#define IDC_STATIC_ERROR                1037
#define IDC_BTN_CONTINUE                1041
#define IDC_STATIC_WARNING              1042
#define IDC_BTN_MOD                     1043
#define IDC_STATIC_NUM                  1044
#define IDC_BTN_REGISTER                1044
#define IDC_STATIC_1                    1045
#define IDC_STATIC_2                    1046
#define IDC_STATIC_3                    1047
#define IDC_STATIC_4                    1048
#define IDC_STATIC_5                    1049
#define IDC_STATIC_6                    1050
#define IDC_STATIC_7                    1051
#define IDC_STATIC_8                    1052
#define IDC_STATIC_9                    1053
#define IDC_STATIC_10                   1054
#define IDC_BTN_RETRY                   1057
#define IDC_BTN_100                     1063
#define IDC_STATIC_0                    1063
#define IDC_BTN_300                     1064
#define IDC_STATIC_00                   1064
#define IDC_BTN_500                     1065
#define IDC_STATIC_INPUT                1065
#define IDC_BTN_800                     1066
#define IDC_BTN_1000                    1067
#define IDC_STATIC_DATE                 1072
#define IDC_STATIC_MONEYTIPS            1073
#define IDC_BTN_CHECK                   1077
#define IDC_EDIT_NAME                   1079
#define IDC_COMBOX_SEX                  1080
#define IDC_EDIT_ADDR                   1081
#define IDC_EDIT_PHONE                  1082
#define IDC_EDIT_DEPOSIT                1085
#define IDC_LIST                        1090
#define IDC_BTN_WRITE                   1093
#define IDC_EDIT_CARDNO                 2004
#define IDC_EDIT_PWD                    2005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        230
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
